// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MireroTicket.Services.Discount.DbContexts;

namespace MireroTicket.Services.Discount.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20201227075915_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("MireroTicket.Services.Discount.Entities.Coupon", b =>
                {
                    b.Property<string>("CouponId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = "dcc03f5f-80d2-4e63-859d-29fc895d201f",
                            Amount = 10,
                            UserId = "e455a3df-7fa5-47e0-8435-179b300d531f"
                        },
                        new
                        {
                            CouponId = "7e7496d3-f7ac-4dd3-bff1-b6d36e4facd5",
                            Amount = 20,
                            UserId = "bbf594b0-3761-4a65-b04c-eec4836d9070"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
