POST https://localhost:6001/api/produce
Content-Type: application/json

"내년에는 잘될거에요."

###
POST https://localhost:6001/api/publish
Content-Type: application/json

"모두에게 알립니다. 내년에는 잘될거에요. 1 "

###
POST https://localhost:5041/api/baskets
Content-Type: application/json

{
  "userId": "0"
}